name: todolist-belajar

services:
  php:
    image: php:8.3-fpm-alpine
    volumes:
      - ./src:/var/www/html
  web:
    image: nginx:stable-bookworm
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:18.1-alpine3.22
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"